### ISSUE TITLE
Persona Template

### ISSUE THREAD

**Issue by jaybeebauer** [jaybeebauer/codefair#16]
Researching users

1. Review the powerpoint opposite to get an overview of the methods that can be used to research users.

2. Read the document Tools for user Research to understand the range of user research tools that are used when developing software products.

3. Which tools/methods do you think are appropriate at the beginning of a website development/redevelopment & why?

You will learn two methods: creating a persona & usability testing.

Creating user personas for your website project

1. Review the powerpoint opposite on what personas are and how to create them.

2. Write down everything you know about your user groups for your website. Complete the interaction grid (see Milestone 2 PPT)

3. Download the persona template and student data information.

4. in your teams, create a persona each to represent  the different types of users who will visit your website.

**Comment by jaybeebauer** [comment]
Still waiting on persona template from Barbara

**Comment by jaybeebauer** [comment]
Hey Mate,

Got links working, need to both do a persona

Download the persona template and student data information.

in your teams, create a persona each to represent  the different types of users who will visit your website.

Under milestone2
Creating your persona.pptx
and the template also there

Need by Sunday

**Comment by jaybeebauer** [comment]
I'm going to do a high school student as the persona, if you'd like to do either Uni student or IT Pro or sponsor?

**Comment by krisbebb** [comment]
Uni Student persona in progress.

**Comment by krisbebb** [comment]
Completed. Will upload with content inventory / strategy additions
