### ISSUE TITLE
Prototype your navigation  - HTML / CSS Wireframe

### ISSUE THREAD

**Issue by krisbebb** [jaybeebauer/codefair#24]
You will need to create BOTH a paper prototype and an HTML/CSS  wireframe

a. Use the resources opposite to find out how to create these various prototypes.

Together, decide on the navigation that is most appropriate for your site
One of you needs to prototype this in paper - use the graphic opposite for ideas for this
The other team members needs to create a wireframe from HTML & CSS that demonstrates the navigation's interactivity.
Ensure you check the project's technical specs when you begin writing the HTML.
At this stage - do not use any colour in your CSS.

**Comment by jaybeebauer** [comment]
I believe they have a misunderstanding of the word wireframe and prototype, but all good I'm going to whip up the "working" wireframe version from html and no colour css tomorrow for the site. But i've updated the wireframe on draw.io.

**Comment by krisbebb** [comment]
Just realised we may need to throw in a "search" function. In the header possibly.

**Comment by jaybeebauer** [comment]
I've updated the html wireframe, please review, also note i'm still working on CSS for mobile phones. I'll get the search function (box) in there soon.

**Comment by krisbebb** [comment]
Cool. I'll have to do a paper wireframe for mobile too.

**Comment by jaybeebauer** [comment]
I've updated responsive design to phones/ etc, couple of issues with display from homepage, can look at in the future, basic wireframe is now there, when you've updated the paper wireframe I can adjust as needed.
